### ISSUE TITLE
Showing search country instead of search state in state searchbar

### ISSUE THREAD

**Issue by bipindubey-technoark** [altafc22/csc_picker#1]
![image](https://user-images.githubusercontent.com/59605232/111603238-26f38780-87fa-11eb-8cba-8fe7d2552c2f.png)

the searchbar should say search state

And i am glad that i am the first person to open issues :)

**Comment by altafc22** [comment]
Updated please use v0.0.8

**Comment by bipindubey-technoark** [comment]
@altafc22 Ok Thanks
