### ISSUE TITLE
Cannot store selected flag icon in database and how to change background of dropdown box ?

### ISSUE THREAD

**Issue by naveenbharadwaj19** [altafc22/csc_picker#15]
I'm trying to store the selected country flag in my database when ever a country is selected i can't able to see the country flag in my debug console as well as in my database why ? . How to change the dropdown box of country ,state ,city ? I want the dropdown box background as yellow and text inside it as white

**Steps tried to reproduce:**
```
CSCPicker(
 flagState: CountryFlag.SHOW_IN_DROP_DOWN_ONLY, // tried CountryFlag.ENABLE
);
```
![country](https://user-images.githubusercontent.com/63662884/114259312-953afc80-99ea-11eb-9bcb-75a8e811ff58.png)
![country_box](https://user-images.githubusercontent.com/63662884/114259297-7d637880-99ea-11eb-978d-ecea8d9baceb.png)
![bg](https://user-images.githubusercontent.com/63662884/114259322-ac79ea00-99ea-11eb-9e12-1af57be0ff52.png)

**Editor :** Visual studio code
**Flutter version :** 2.0.2

**Comment by altafc22** [comment]
You need to restart application once you changed the flagstate it will work
perfectly once you restart the application.

Flag is generated by country code to in output you can see the flag and in
debug you can see the country code.

And thanks for nice suggestion I will add drop-down color functionality in
package you will get it in next version.

**Comment by naveenbharadwaj19** [comment]
@altafc22 Restarted the application but nothing changed
