### ISSUE TITLE
customize height and padding in dropdown and allow to change the border as well

### ISSUE THREAD

**Issue by bipindubey-technoark** [altafc22/csc_picker#2]
I saw your component today and it is really nice and i wanted it .... i have done R&D on it from last 10-15 days but nothing was so as good as your component.
I want to customize little bit of your component . i want just ui changes so that it looks as other elements in projects,

**Comment by altafc22** [comment]
Yes, we are working on that in next version this feature will be available

**Comment by bipindubey-technoark** [comment]
Ok thanks for your reply @altafc22 
please update here

**Comment by altafc22** [comment]
New version v0.2.0 is released with DropDown Decoration and text styling features.

**Comment by bipindubey-technoark** [comment]
@altafc22 Ok thanks

**Comment by bipindubey-technoark** [comment]
@altafc22 I have to use padding between border of dropdown and content .. how to do it

**Comment by UmerAbbasi1515** [comment]
how we can update height and width?
