### ISSUE TITLE
after clicking on close in modal the all dropdown resets its values

### ISSUE THREAD

**Issue by bipindubey-technoark** [altafc22/csc_picker#3]
i have selected country india and state as gujrat and then i again go to country dropdown and then in modal i click on close then country and state then it resets its value to initial stage .... it should store the previous values

![image](https://user-images.githubusercontent.com/59605232/111610991-f879aa80-8801-11eb-82f8-264458d7723e.png)

after clicking on close link in country modal

![image](https://user-images.githubusercontent.com/59605232/111611028-04fe0300-8802-11eb-9352-bed6b49b25ff.png)

**Comment by altafc22** [comment]
Field Reset issues resolved now, kindly use v0.2.1
