### ISSUE TITLE
Request: Method to customize default texts

### ISSUE THREAD

**Issue by soullest** [altafc22/csc_picker#30]
Hello and thank you very much for developing this module, I have a small request to be able to customize the texts that are shown in the search boxes such as "State", "Search State", "Search Country" and "Search city" this would allow internationalization correctly these labels and increase the potential of this module. Thank you

**Comment by altafc22** [comment]
Hi @soullest, thank you suggesion. Definately we will add this feature in library. You will receive this feature in next version

**Comment by soullest** [comment]
Wow! Thanks for your really fast answer, it's much appreciated!

**Comment by altafc22** [comment]
Hi @soullest, now this option is available in csc picker you can use it as shown below

```
 ///placeholders for dropdown search field
                  countrySearchPlaceholder: "Country",
                  stateSearchPlaceholder: "State",
                  citySearchPlaceholder: "City",

                  ///labels for dropdown
                  countryDropdownLabel: "*Country",
                  stateDropdownLabel: "*State",
                  cityDropdownLabel: "*City",
```
