### ISSUE TITLE
initialize default value to country and state dropdown

### ISSUE THREAD

**Issue by bipindubey-technoark** [altafc22/csc_picker#4]
I want to initize the default value to dropdown
Eg. United States Of America as country and Taxes as a state.
@altafc22 can you include field for it
Thanks

**Comment by bipindubey-technoark** [comment]
@altafc22 any update?

**Comment by bipindubey-technoark** [comment]
@altafc22 Everything is done i am just waiting for this functionality, It is a basic usecase which every component have.
Can you please try to fixx this issue asap

**Comment by yashhalgaonkar** [comment]
Even I want this functionality. Please can the maintainers add this asap.

**Comment by Jamesweng** [comment]
any updates on this feature?

**Comment by altafc22** [comment]
Sorry for delay guys, i will add this functionality in some days.

**Comment by bipindubey-technoark** [comment]
@altafc22 Whenver it is done please let us know.
Thanks

**Comment by altafc22** [comment]
Sure

**Comment by bipindubey-technoark** [comment]
Actually client wants this issue urgently.
So can you please give me some deadline like how much time it will take to do this??
I have only 1 day left .

Thanks @altafc22

**Comment by altafc22** [comment]
Hello All, 
Now you can select Default country in csc picker to achieve funtionality please add below lines in your code

`///Default Country
 defaultCountry: DefaultCountry.India, `

**Comment by bipindubey-technoark** [comment]
@altafc22 is there any way i can provide string to that field.
Eg. I am  getting India as string value from backend so i have to convert string to DefaultCountry object . how to do this??

**Comment by bipindubey-technoark** [comment]
@altafc22 i have to initilize default state also
