### ISSUE TITLE
get only country name as value instead getting country code with flag and country name

### ISSUE THREAD

**Issue by bipindubey-technoark** [altafc22/csc_picker#5]
on country change i am getting country code with flag and full country name

can i get only country name 

EG. 
CURRENT BEHAVIOUR :
IN INDIAN FLAG INDIA

EXPECTED BEHAVIOUR:
INDIA

**Comment by altafc22** [comment]
hi @bipindubey-technoark, thanks for using csc picker. you can use showFlag parmeter to enable disable flag in app

eg. showFlag | Boolean - toggle country flag

**Comment by bipindubey-technoark** [comment]
I want to show flag in dropdown but i want to stored only country name as value
 in variable

**Comment by altafc22** [comment]
thanks for suggesting this feature you can get this thing in new versions which is 
v0.0.9 
package is updated please add version v0.0.9 in your project

**Comment by bipindubey-technoark** [comment]
Ok Thanks @altafc22

**Comment by bipindubey-technoark** [comment]
Ok for the other people who might get this same issue in future 

just use this
                          flagState: CountryFlag.SHOW_IN_DROP_DOWN_ONLY,
                          
                          it has 3 options 
                            CountryFlag.SHOW_IN_DROP_DOWN_ONLY,
                            CountryFlag.ENABLE,
                            CountryFlag.DISABLE

**Comment by bipindubey-technoark** [comment]
@altafc22 i m still getting space before the country name 

I have used this 
                        CountryFlag.SHOW_IN_DROP_DOWN_ONLY,

**Comment by bipindubey-technoark** [comment]
![image](https://user-images.githubusercontent.com/59605232/112302796-7c7bd880-8cc1-11eb-857e-ffe9ebdd57e0.png)
