### ISSUE TITLE
Background color of state and country dropdown is not matching 

### ISSUE THREAD

**Issue by bipindubey-technoark** [altafc22/csc_picker#6]
![image](https://user-images.githubusercontent.com/59605232/112303704-9b2e9f00-8cc2-11eb-9372-560469be3f51.png)

Why is the background color are not same for country and state ..
Is their any way to change this??

**Comment by altafc22** [comment]
once you select country then it will enables state and background color will become white as country same for state and city

we are working on dropdown style feature you will get this in next version

**Comment by bipindubey-technoark** [comment]
Ohh i got it now
Thanks
