### ISSUE TITLE
OnCountry changed calling build method again which is rerendering other field as well

### ISSUE THREAD

**Issue by bipindubey-technoark** [altafc22/csc_picker#7]
I have firstname, lastName ,country and state.

I have initialValue in firstname as john and lastname as warner,

now i change my firstname from john to john123 and then select country then firstname again set to john.

This is because on country changed it is calling build methof again which is reinitializing the value of other field.

**Comment by altafc22** [comment]
This issue is not related package, kindly use latest version of package.

**Comment by bipindubey-technoark** [comment]
@altafc22 but on country change it is calling build method again
Can you check that for me and tell me
