### ISSUE TITLE
Unable to select cities or states

### ISSUE THREAD

**Issue by Henry0149** [altafc22/csc_picker#81]
Both Properties showStates and showCities are set to true, yet i cant get the dropdown.

                                  SizedBox(
                                    width: 370.w,
                                    height: 120.h,
                                    child: CSCPicker(
                                      key: _cscPickerKey,
                                      // defaultCountry: CscCountry.United_States,
                                      // disableCountry: true,
                                      showCities: true,
                                      showStates: true,
                                      countrySearchPlaceholder: "Country",
                                      stateSearchPlaceholder: "State",
                                      citySearchPlaceholder: "City",
                                      countryDropdownLabel: "Country",
                                      stateDropdownLabel: "*State",
                                      cityDropdownLabel: "*City",
                                      // disabledDropdownDecoration: BoxDecoration(
                                      //   borderRadius: BorderRadius.all(
                                      //     Radius.circular(30.r),
                                      //   ),
                                      //   color: Colors.grey.shade300,
                                      //   border: Border.all(
                                      //       color: Colors.grey.shade300,
                                      //       width: 1),
                                      // ),
                                      dropdownDecoration: BoxDecoration(
                                        borderRadius: BorderRadius.all(
                                          Radius.circular(30.r),
                                        ),
                                        color: Colors.white,
                                        border: Border.all(
                                          color: Colors.grey.shade300,
                                          width: 1,
                                        ),
                                      ),
                                      //flagState: CountryFlag.ENABLE,
                                      currentCountry: "US",
                                      countryFilter: const [
                                        CscCountry.United_States
                                      ],
                                      selectedItemStyle: GoogleFonts.inter(
                                        color: Colors.black,
                                        fontSize: 14,
                                      ),

                                      ///DropdownDialog Heading style [OPTIONAL PARAMETER]
                                      dropdownHeadingStyle: GoogleFonts.inter(
                                          color: Colors.black,
                                          fontSize: 17,
                                          fontWeight: FontWeight.bold),

                                      ///DropdownDialog Item style [OPTIONAL PARAMETER]
                                      dropdownItemStyle: GoogleFonts.inter(
                                        color: Colors.black,
                                        fontSize: 14,
                                      ),
                                      dropdownDialogRadius: 30.0,
                                      onStateChanged: (value) {
                                        setState(() {
                                          ///store value in state variable
                                          stateValue = value;
                                        });
                                      },

                                      ///triggers once city selected in dropdown
                                      onCityChanged: (value) {
                                        setState(() {
                                          ///store value in city variable
                                          cityValue = value;
                                        });
                                      },
                                    ),
                                  ),
   This is my code

Drop Down are suppose to be enabled

 - Device: Samsung A23
 - OS: Android 13, One UI: 5.1

**Comment by haleem13** [comment]
did you figure out how to do it

**Comment by Henry0149** [comment]
If you have a country set by default, it will disable other fields. You have to reselect the country, then fields will be enabled
