### ISSUE TITLE
flagstate property issue

### ISSUE THREAD

**Issue by vaagmay** [altafc22/csc_picker#9]
when I enable the property of **flagstate** it not displays the flag of the relevant country

**Comment by altafc22** [comment]
Thanks for the update will check what's the issue, If any issue found definitely it will resolve in next version

**Comment by vaagmay** [comment]
make it fast as soon as possible . Thank you :)

**Comment by altafc22** [comment]
can you please explain the issue in detail

**Comment by hjudoo** [comment]
its displaying the correct country for me, I've checked couple of them first, canada and last one on the list all 3 displaying the correct flag. Which country are you selecting?

**Comment by altafc22** [comment]
Closing this issue, because there is no clear discription about issue.  i have tested for many countries, packege is showing correct flags.
